on: push

jobs:
  check_style:
    name: Static formatters and analyzers
    runs-on: ubuntu-latest
    container: vvinokurshin/project_cpp:v1
    steps:
      - uses: actions/checkout@v3
      - name: Run formatters and analyzers before build
        run: |
          chmod -R 755 ./linters && make check_before_build

      - name: Run formatters and analyzers after build
        run: |
          chmod -R 755 ./linters && make check_object_files
  build:
    # todo
  test:
    # todo
  memtest:
    # todo